version: "3"
services:
  mymongo:
    image: mongo
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
  grpc-server:
    image: vikashsurin/mongo-conn:v3
