apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: grpc-server
  name: grpc-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grpc-server
  template:
    metadata:
      labels:
        app: grpc-server
    spec:
      containers:
        - image: vikashsurin/grpc-server:latest
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          name: grpc-server
          ports:
            - containerPort: 8080
          env:
            - name: NAME
              value: vikashsurin
            - name: URI
              value: mongodb://mongodb-server-service:27017
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: grpc-server-service
  name: grpc-server-service
spec:
  type: ClusterIP
  selector:
    app: grpc-server
  ports:
    - targetPort: 8080
      protocol: TCP
      port: 8080
  sessionAffinity: None
